
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:23 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armclang 
      Build flags: --target=arm-arm-none-eabi;-mcpu=Cortex-M7;-mfpu=fpv5-sp-d16;-mfloat-abi=hard
      Id flags: -c;--target=arm-arm-none-eabi 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is ARMClang, found in:
        /Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/4.0.2/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1271 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" matched "armclang":
      Product: Hardware Success Kit (Early Access)
      Component: Arm Compiler for Embedded 6.23
      Tool: armclang [5f103000]
      
      Target: unspecified-arm-none-none
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz"
      binary: "/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz"
    cmakeVariables:
      CMAKE_CXX_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "--target=arm-arm-none-eabi -mcpu=Cortex-M7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/opt/cmsis-toolbox/etc/CMakeASM"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz'
        
        Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_b55d6
        [1/2] /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=Cortex-M7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -c /opt/homebrew/share/cmake/Modules/CMakeCCompilerABI.c
        Product: Hardware Success Kit (Early Access)
        Component: Arm Compiler for Embedded 6.23
        Tool: armclang [5f103000]
        
        Target: arm-arm-none-eabi
         (in-process)
         "/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armclang" -cc1 -triple thumbv7em-arm-none-eabihf -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m7 -target-feature -vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz -resource-dir /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/lib/clang/20 -dependency-file CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -x c /opt/homebrew/share/cmake/Modules/CMakeCCompilerABI.c
        Arm Compiler for Embedded 6.23 -cc1 default target aarch64-arm-none-eabi
        #include "..." search starts here:
        #include <...> search starts here:
         /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include
        End of search list.
        [2/2] : && /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armar --create -cr libcmTC_b55d6.a  CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:191 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include]
        end of search list found
        collapse include dir [/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include] ==> [/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/include]
        implicit include dirs: [/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:23 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink|;ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(armlink|;ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)))("|,| |$)]
        ignore line: [Change Dir: '/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz']
        ignore line: []
        ignore line: [Run Build Command(s): /opt/homebrew/bin/ninja -v cmTC_b55d6]
        ignore line: [[1/2] /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=Cortex-M7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -c /opt/homebrew/share/cmake/Modules/CMakeCCompilerABI.c]
        ignore line: [Product: Hardware Success Kit (Early Access)]
        ignore line: [Component: Arm Compiler for Embedded 6.23]
        ignore line: [Tool: armclang [5f103000]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "/Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armclang" -cc1 -triple thumbv7em-arm-none-eabihf -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m7 -target-feature -vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/chrsei01/02_Git/MDK-Packs/RDM2025/uv2csolution/tmp/1/CMakeFiles/CMakeScratch/TryCompile-MIm0vz -resource-dir /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/lib/clang/20 -dependency-file CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o -x c /opt/homebrew/share/cmake/Modules/CMakeCCompilerABI.c]
        ignore line: [Arm Compiler for Embedded 6.23 -cc1 default target aarch64-arm-none-eabi]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/../include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /Users/chrsei01/Arm_Compiler_for_Embedded_6_23_0/bin/armar --create -cr libcmTC_b55d6.a  CMakeFiles/cmTC_b55d6.dir/CMakeCCompilerABI.o && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
